version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka-1
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:9092,LOCAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            access-log:
              enabled: false
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8082:8080
    links:
      - kafka

  producer:
    build: producer/
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_TOPIC: "sample-retry"
    depends_on:
      - kafka

  no-retry-consumer:
    build: retriable-consumer/
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_TOPIC: "sample-retry"
      KAFKA_PARTITION: 4
      KAFKA_NUMBER_RETRY: 0
      KAFKA_GROUP_ID: "no-retriable-consumer-group"
      KAFKA_RESET_STRATEGY: "earliest"
      KAFKA_MAX_POLL_INTERVAL_MS: 300000
      KAFKA_EXTERNAL_SERVICE_URL: "http://service/service"
      KAFKA_COMMIT_INTERVAL_MS: 10000
    depends_on:
      - kafka

  limited-retries-consumer:
    build: retriable-consumer/
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_TOPIC: "sample-retry"
      KAFKA_PARTITION: 4
      KAFKA_NUMBER_RETRY: 10
      KAFKA_GROUP_ID: "limited-retriable-consumer-group"
      KAFKA_RESET_STRATEGY: "earliest"
      KAFKA_MAX_POLL_INTERVAL_MS: 300000
      KAFKA_EXTERNAL_SERVICE_URL: "http://service/service"
      KAFKA_COMMIT_INTERVAL_MS: 10000
    depends_on:
      - kafka

  infinite-retries-consumer:
    build: retriable-consumer/
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_TOPIC: "sample-retry"
      KAFKA_PARTITION: 4
      KAFKA_NUMBER_RETRY: -1
      KAFKA_GROUP_ID: "infinite-retriable-consumer-group"
      KAFKA_RESET_STRATEGY: "earliest"
      KAFKA_MAX_POLL_INTERVAL_MS: 300000
      KAFKA_EXTERNAL_SERVICE_URL: "http://service/service"
      KAFKA_COMMIT_INTERVAL_MS: 10000
    depends_on:
      - kafka

  service:
    build: external-web-api/
    container_name: service
    hostname: service
    environment:
      PERCENT_OF_ERROR: 75